# Generated by Django 3.2.9 on 2021-11-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usersocialmedia_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialMedia',
        ),
    ]
