# Generated by Django 3.2.9 on 2021-11-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211116_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
