# Generated by Django 3.2.9 on 2021-11-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_certificate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='issuer',
        ),
    ]
