# Generated by Django 4.0.5 on 2022-06-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211121_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
