# Generated by Django 4.0.5 on 2022-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_blog_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome')),
                ('score', models.IntegerField(blank=True, default=80, null=True, verbose_name='Nível')),
                ('image', models.FileField(blank=True, null=True, upload_to='skills')),
                ('is_key_skill', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Habilidade interpessoal',
                'verbose_name_plural': 'Habilidades interpessoais',
                'ordering': ['-score'],
            },
        ),
    ]
