# Generated by Django 4.0.5 on 2022-06-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_softskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-score'], 'verbose_name': 'Habilidade Técnica', 'verbose_name_plural': 'Habilidades Técnicas'},
        ),
    ]
